#pragma once

//Gamefield

#define FIELD_WIDTH 12
#define FIELD_HEIGHT 16


//Ball

#define ONE_STEP 0.01
#define BALL_LIMIT 20

//Block

#define REGULAR_BLOCK_HEALTH 1
#define STRONG_BLOCK_HEALTH 3
#define VERY_STRONG_BLOCK_HEALTH 100
#define INDESTRUCTIBLE_BLOCK_HEALTH 0

//Powerups

#define POWERUP_COLLECT_RANGE 0.5

#define TRIPLE_PWUP_BALL_NUMBER 3
#define BIGBALL_PWUP_RADIUS_MULTIPLER 2
#define EXTRALIVE_PWUP_LIVE_AMT 1
#define BIGRACKET_PWUP_INCRASE 1.4
#define SMALLRACKET_PWUP_DECRASE 0.6
#define FASTBALL_PWUP_INCRASE 1.5
#define SLOWBALL_PWUP_DECRASE 0.5

enum BlockType { REGULAR, STRONG, VERY_STRONG, INDESTRUCTIBLE };
